import "@mdi/font/css/materialdesignicons.css";

export const icons = {
  facebook: "mdi mdi-facebook",
  twitter: "mdi mdi-twitter",
  googlePlus: "mdi mdi-google-plus",
  instagram: "mdi mdi-instagram",
  linkedin: "mdi mdi-linkedin",
  home: "mdi mdi-home",
  chevronUp: "mdi mdi-chevron-up",
  chevronLeft: "mdi mdi-chevron-left",
  chevronRight: "mdi mdi-chevron-right",
  user: "mdi mdi-account",
  userTie: "mdi mdi-account-tie",
  key: "mdi mdi-key",
  phone: "mdi mdi-phone",
  cellphone: "mdi mdi-cellphone",
  squareRoot: "mdi mdi-square-root",
  login: "mdi mdi-login",
  logout: "mdi mdi-logout",
  register: "mdi mdi-account-plus",
  file: "mdi mdi-file",
  language: "mdi mdi-translate",
  dollar: "mdi mdi-currency-usd",
  newspaper: "mdi mdi-newspaper",
  clock: "mdi mdi-clock",
  bell: "mdi mdi-bell",
  infoCircle: "mdi mdi-information",
  folder: "mdi mdi-folder",
  delete: "mdi mdi-delete",
  edit: "mdi mdi-pencil",
  download: "mdi mdi-download",
  search: "mdi mdi-magnify",
  calendarDay: "mdi mdi-calendar-today",
  tick: "mdi mdi-check",
  clear: "mdi mdi-delete",
  cancel: "mdi mdi-close",
  info: "mdi mdi-information",
  handshake: "mdi mdi-hand-heart",
  fileDocumentBox: "mdi mdi-file-document-box",
  wallet: "mdi mdi-wallet",
  messageProcessing: "mdi mdi-message-processing",
  notificationClearAll: "mdi mdi-notification-clear-all",
  email: "mdi mdi-email",
  send: "mdi mdi-send",
  scaleBalance: "mdi mdi-scale-balance",
  setting: "mdi mdi-settings-outline"
};
